@echo off
echo Building all services...

echo Building auth-service...
docker build -t ai-test-auth-service -f services/auth-service/Dockerfile . || echo auth-service failed

echo Building user-service...
docker build -t ai-test-user-service -f services/user-service/Dockerfile . || echo user-service failed

echo Building project-service...
docker build -t ai-test-project-service -f services/project-service/Dockerfile . || echo project-service failed

echo Building testcase-service...
docker build -t ai-test-testcase-service -f services/testcase-service/Dockerfile . || echo testcase-service failed

echo Building defect-service...
docker build -t ai-test-defect-service -f services/defect-service/Dockerfile . || echo defect-service failed

echo Building requirement-service...
docker build -t ai-test-requirement-service -f services/requirement-service/Dockerfile . || echo requirement-service failed

echo Building dashboard-service...
docker build -t ai-test-dashboard-service -f services/dashboard-service/Dockerfile . || echo dashboard-service failed

echo Building strategy-service...
docker build -t ai-test-strategy-service -f services/strategy-service/Dockerfile . || echo strategy-service failed

echo Building frontend...
docker build -t ai-test-frontend -f services/frontend/Dockerfile . || echo frontend failed

echo All builds completed!
docker images | findstr ai-test